apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shoppingingress-network-policy
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: svc-contour-domain-c8
    - podSelector:
        matchLabels:
          app: contour
    ports:
    - protocol: TCP
      port: 8080
    - protocol: TCP
      port: 80

