apiVersion: vmoperator.vmware.com/v1alpha3
kind: VirtualMachine
metadata:
  annotations:
    virtualmachine.vmoperator.vmware.com/first-boot-done: 'true'
    vmoperator.vmware.com/backup-version: '1769660355653'
    vmoperator.vmware.com/created-at-build-version: 0.1.0+c6d1028+1.8.6+3fa500dd+24727344
    vmoperator.vmware.com/created-at-schema-version: v1alpha4
    vmoperator.vmware.com/last-resized-vm-class: >-
      {"name":"best-effort-small","uid":"6b2d443b-fd4b-4ac2-8709-ab8d9891ad0e","generation":1}
    vmoperator.vmware.com/manager-id: 84953890-6288-4dd6-9ca8-d6f7572cdb29
  creationTimestamp: '2026-01-29T04:17:58Z'
  finalizers:
    - vmoperator.vmware.com/virtualmachine
  generation: 1
  labels:
    topology.kubernetes.io/zone: z-wld-a
    vm-lb-dev: vm-lb-selector
    vm-selector: oc-mysql
  managedFields:
    - apiVersion: vmoperator.vmware.com/v1alpha3
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:topology.kubernetes.io/zone: {}
            f:vm-lb-dev: {}
            f:vm-selector: {}
        f:spec:
          .: {}
          f:bootstrap:
            .: {}
            f:cloudInit:
              .: {}
              f:rawCloudConfig:
                .: {}
                f:key: {}
                f:name: {}
          f:className: {}
          f:imageName: {}
          f:network:
            .: {}
            f:domainName: {}
            f:hostName: {}
            f:nameservers: {}
          f:powerOffMode: {}
          f:powerState: {}
          f:restartMode: {}
          f:storageClass: {}
          f:suspendMode: {}
      manager: Mozilla
      operation: Update
      time: '2026-01-29T04:17:58Z'
    - apiVersion: vmoperator.vmware.com/v1alpha4
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:virtualmachine.vmoperator.vmware.com/first-boot-done: {}
            f:vmoperator.vmware.com/backup-version: {}
            f:vmoperator.vmware.com/last-resized-vm-class: {}
            f:vmoperator.vmware.com/manager-id: {}
          f:finalizers:
            .: {}
            v:"vmoperator.vmware.com/virtualmachine": {}
      manager: manager
      operation: Update
      time: '2026-01-29T04:19:16Z'
    - apiVersion: vmoperator.vmware.com/v1alpha4
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:biosUUID: {}
          f:changeBlockTracking: {}
          f:class:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
          f:conditions: {}
          f:hardwareVersion: {}
          f:host: {}
          f:instanceUUID: {}
          f:network:
            .: {}
            f:config:
              .: {}
              f:dns:
                .: {}
                f:domainName: {}
                f:hostName: {}
                f:nameservers: {}
              f:interfaces: {}
            f:interfaces: {}
            f:ipStacks: {}
            f:primaryIP4: {}
          f:powerState: {}
          f:storage:
            .: {}
            f:usage:
              .: {}
              f:disks: {}
              f:other: {}
              f:total: {}
          f:uniqueID: {}
          f:volumes:
            .: {}
            k:{"name":"oc-mysql","type":"Classic"}:
              .: {}
              f:attached: {}
              f:diskUUID: {}
              f:limit: {}
              f:name: {}
              f:type: {}
              f:used: {}
          f:zone: {}
      manager: manager
      operation: Update
      subresource: status
      time: '2026-02-03T23:52:10Z'
  name: oc-mysql
  namespace: dev-c5545
  resourceVersion: '22360316'
  uid: 3364205e-23ec-42db-8077-bf6b81416bd2
spec:
  biosUUID: 594e7b93-1eac-4434-a5a5-86e9624badf7
  bootstrap:
    cloudInit:
      instanceID: 594e7b93-1eac-4434-a5a5-86e9624badf7
      rawCloudConfig:
        key: user-data
        name: oc-mysql-bootstrap-secret
  className: best-effort-small
  image:
    kind: VirtualMachineImage
    name: vmi-fd3a21a6b77eb7a32
  imageName: vmi-fd3a21a6b77eb7a32
  instanceUUID: 7f3e9a0b-04c3-4463-8c60-4366afdfc29c
  network:
    domainName: vcf.lab
    hostName: oc-mysql
    interfaces:
      - name: eth0
        network:
          apiVersion: crd.nsx.vmware.com/v1alpha1
          kind: SubnetSet
          name: ''
    nameservers:
      - 8.8.8.8
  powerOffMode: TrySoft
  powerState: PoweredOn
  restartMode: TrySoft
  storageClass: cluster-wld01-01a-storage-policy
  suspendMode: TrySoft
status:
  biosUUID: 594e7b93-1eac-4434-a5a5-86e9624badf7
  changeBlockTracking: false
  class:
    apiVersion: vmoperator.vmware.com/v1alpha4
    kind: VirtualMachineClass
    name: best-effort-small
  conditions:
    - lastTransitionTime: '2026-02-03T23:52:09Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineTools
    - lastTransitionTime: '2026-01-29T04:19:16Z'
      message: 'Backup version: 1769660355653'
      reason: 'True'
      status: 'True'
      type: VirtualMachineBackupUpToDate
    - lastTransitionTime: '2026-01-29T04:19:15Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineReconcileReady
    - lastTransitionTime: '2026-01-29T04:19:15Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineClassConfigurationSynced
    - lastTransitionTime: '2026-01-29T04:19:15Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: GuestCustomization
    - lastTransitionTime: '2026-01-29T04:19:15Z'
      message: ''
      reason: NoBootstrapStatus
      status: Unknown
      type: GuestBootstrap
    - lastTransitionTime: '2026-01-29T04:19:11Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineCreated
    - lastTransitionTime: '2026-01-29T04:18:03Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineNetworkReady
    - lastTransitionTime: '2026-01-29T04:18:03Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineConditionPlacementReady
    - lastTransitionTime: '2026-01-29T04:17:59Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineStorageReady
    - lastTransitionTime: '2026-01-29T04:17:59Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineClassReady
    - lastTransitionTime: '2026-01-29T04:17:59Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineBootstrapReady
    - lastTransitionTime: '2026-01-29T04:02:51Z'
      message: ''
      reason: 'True'
      status: 'True'
      type: VirtualMachineImageReady
  hardwareVersion: 22
  host: esx-07a.site-a.vcf.lab
  instanceUUID: 7f3e9a0b-04c3-4463-8c60-4366afdfc29c
  network:
    config:
      dns:
        domainName: vcf.lab
        hostName: oc-mysql
        nameservers:
          - 8.8.8.8
      interfaces:
        - dns:
            nameservers:
              - 8.8.8.8
          ip:
            addresses:
              - 192.173.237.35/27
            gateway4: 192.173.237.33
          name: eth0
    interfaces:
      - deviceKey: 4000
        ip:
          addresses:
            - address: 192.173.237.35
              state: preferred
            - address: fe80::650:56ff:fe00:a000
              state: unknown
          macAddr: 04:50:56:00:a0:00
        name: eth0
    ipStacks:
      - dns:
          domainName: .
          hostName: mysql
          nameservers:
            - 8.8.8.8
          searchDomains:
            - .
        ipRoutes:
          - gateway:
              address: 192.173.237.33
              device: '0'
            networkAddress: 0.0.0.0/0
          - gateway:
              device: '0'
            networkAddress: 192.173.237.32/27
    primaryIP4: 192.173.237.35
  powerState: PoweredOn
  storage:
    usage:
      disks: 10Gi
      other: '0'
      total: 10Gi
  uniqueID: vm-8027
  volumes:
    - attached: true
      diskUUID: 6000C29c-3635-41fe-b598-c342c4129c87
      limit: 10Gi
      name: oc-mysql
      type: Classic
      used: 10Gi
  zone: z-wld-a
